use std::sync::{Arc, Mutex};

use chrono::Utc;
use tokio::sync::{mpsc, watch};
use zbus::{interface, object_server::SignalContext};

use twitch_backend::{
    handle::{LoginProgress, RawDisplayData},
    AuthCommand,
};

use crate::{dto::PlasmoidState, plasmoid_state::compute_plasmoid_state};

pub const OBJECT_PATH: &str = "/org/twitch/TwitchTray";

/// Request to open a Tauri window, sent to main.rs over a channel.
pub enum WindowRequest {
    OpenSettings,
    OpenStreamerSettings {
        user_login: String,
        display_name: String,
    },
}

/// D-Bus service implementing `org.twitch.TwitchTray1` at [`OBJECT_PATH`].
///
/// Holds channels only — no `AppHandle`, no Tauri types.
pub struct DbusService {
    pub state: Arc<Mutex<PlasmoidState>>,
    pub auth_cmd_tx: mpsc::UnboundedSender<AuthCommand>,
    pub window_tx: mpsc::Sender<WindowRequest>,
    /// Seam for testing; production uses `open::that`.
    pub open_url: Arc<dyn Fn(&str) + Send + Sync>,
    pub cancel_login_tx: mpsc::Sender<()>,
}

#[interface(interface = "org.twitch.TwitchTray1")]
impl DbusService {
    /// JSON-serialised `PlasmoidState`. Updated whenever state changes.
    /// `emits_changed_signal = "false"` prevents the macro from auto-generating
    /// a `state_changed` helper (which would conflict with our explicit signal).
    #[zbus(property(emits_changed_signal = "false"))]
    fn state(&self) -> String {
        serde_json::to_string(&*self.state.lock().unwrap()).unwrap_or_default()
    }

    async fn login(&self) {
        self.do_login();
    }

    async fn logout(&self) {
        self.do_logout();
    }

    async fn open_stream(&self, user_login: String) {
        self.do_open_stream(&user_login);
    }

    async fn open_settings(&self) {
        self.do_open_settings().await;
    }

    async fn open_streamer_settings(&self, user_login: String, display_name: String) {
        self.do_open_streamer_settings(user_login, display_name)
            .await;
    }

    async fn cancel_login(&self) {
        self.do_cancel_login().await;
    }

    /// Emitted whenever `State` changes.
    /// Named `emit_state_changed` in Rust to avoid colliding with the
    /// property-change helper `state_changed` auto-generated by the macro.
    #[zbus(signal, name = "StateChanged")]
    async fn emit_state_changed(ctxt: &SignalContext<'_>, state: String) -> zbus::Result<()>;
}

/// Internal methods — callable directly in unit tests without a D-Bus connection.
impl DbusService {
    pub fn do_login(&self) {
        let _ = self.auth_cmd_tx.send(AuthCommand::Login);
    }

    pub fn do_logout(&self) {
        let _ = self.auth_cmd_tx.send(AuthCommand::Logout);
    }

    pub fn do_open_stream(&self, user_login: &str) {
        (self.open_url)(&format!("https://twitch.tv/{user_login}"));
    }

    pub async fn do_open_settings(&self) {
        let _ = self.window_tx.send(WindowRequest::OpenSettings).await;
    }

    pub async fn do_open_streamer_settings(&self, user_login: String, display_name: String) {
        let _ = self
            .window_tx
            .send(WindowRequest::OpenStreamerSettings {
                user_login,
                display_name,
            })
            .await;
    }

    pub async fn do_cancel_login(&self) {
        let _ = self.cancel_login_tx.send(()).await;
    }
}

/// Spawns a background task that watches `display_rx` and `login_progress_rx`,
/// recomputes [`PlasmoidState`], and emits the `StateChanged` D-Bus signal.
///
/// Obtain the `SignalContext<'static>` after registering the interface:
/// ```ignore
/// let iface_ref = conn.object_server()
///     .interface::<_, DbusService>(OBJECT_PATH).await?;
/// let ctxt = iface_ref.signal_context().to_owned();
/// ```
pub fn spawn_state_watcher(
    service_state: Arc<Mutex<PlasmoidState>>,
    mut display_rx: watch::Receiver<RawDisplayData>,
    mut login_progress_rx: watch::Receiver<Option<LoginProgress>>,
    ctxt: SignalContext<'static>,
) -> tokio::task::JoinHandle<()> {
    tokio::spawn(async move {
        loop {
            tokio::select! {
                result = display_rx.changed() => { if result.is_err() { break; } }
                result = login_progress_rx.changed() => { if result.is_err() { break; } }
            }
            let raw = display_rx.borrow_and_update().clone();
            let lp = login_progress_rx.borrow_and_update().clone();
            let new_state = compute_plasmoid_state(raw, lp.as_ref(), Utc::now());
            let json = serde_json::to_string(&new_state).unwrap_or_default();
            *service_state.lock().unwrap() = new_state;
            let _ = DbusService::emit_state_changed(&ctxt, json).await;
        }
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::dto::{LiveSectionDto, LoginStateDto, PlasmoidState, ScheduleSectionDto};
    use twitch_backend::AuthCommand;

    fn default_state() -> PlasmoidState {
        PlasmoidState {
            authenticated: false,
            login_state: LoginStateDto::Idle,
            live: LiveSectionDto {
                visible: vec![],
                overflow: vec![],
            },
            categories: vec![],
            schedule: ScheduleSectionDto {
                lookahead_hours: 24,
                loaded: false,
                visible: vec![],
                overflow: vec![],
            },
        }
    }

    struct TestService {
        service: DbusService,
        auth_rx: mpsc::UnboundedReceiver<AuthCommand>,
        window_rx: mpsc::Receiver<WindowRequest>,
        cancel_rx: mpsc::Receiver<()>,
        url_rx: std::sync::mpsc::Receiver<String>,
    }

    fn make_test_service() -> TestService {
        let (auth_tx, auth_rx) = mpsc::unbounded_channel();
        let (window_tx, window_rx) = mpsc::channel(4);
        let (cancel_tx, cancel_rx) = mpsc::channel(1);
        let (url_tx, url_rx) = std::sync::mpsc::channel();

        let service = DbusService {
            state: Arc::new(Mutex::new(default_state())),
            auth_cmd_tx: auth_tx,
            window_tx,
            open_url: Arc::new(move |url: &str| {
                let _ = url_tx.send(url.to_string());
            }),
            cancel_login_tx: cancel_tx,
        };

        TestService {
            service,
            auth_rx,
            window_rx,
            cancel_rx,
            url_rx,
        }
    }

    #[tokio::test]
    async fn login_method_sends_auth_command_login() {
        let mut t = make_test_service();
        t.service.do_login();
        assert!(matches!(t.auth_rx.try_recv().unwrap(), AuthCommand::Login));
    }

    #[tokio::test]
    async fn logout_method_sends_auth_command_logout() {
        let mut t = make_test_service();
        t.service.do_logout();
        assert!(matches!(t.auth_rx.try_recv().unwrap(), AuthCommand::Logout));
    }

    #[tokio::test]
    async fn open_stream_opens_correct_url() {
        let t = make_test_service();
        t.service.do_open_stream("ninja");
        let url = t.url_rx.recv().unwrap();
        assert_eq!(url, "https://twitch.tv/ninja");
    }

    #[tokio::test]
    async fn open_settings_sends_window_request() {
        let mut t = make_test_service();
        t.service.do_open_settings().await;
        assert!(matches!(
            t.window_rx.try_recv().unwrap(),
            WindowRequest::OpenSettings
        ));
    }

    #[tokio::test]
    async fn open_streamer_settings_sends_window_request_with_login_and_name() {
        let mut t = make_test_service();
        t.service
            .do_open_streamer_settings("ninja".to_string(), "Ninja".to_string())
            .await;
        let req = t.window_rx.try_recv().unwrap();
        assert!(matches!(
            req,
            WindowRequest::OpenStreamerSettings { ref user_login, ref display_name }
            if user_login == "ninja" && display_name == "Ninja"
        ));
    }

    #[tokio::test]
    async fn cancel_login_sends_cancel_signal() {
        let mut t = make_test_service();
        t.service.do_cancel_login().await;
        assert!(t.cancel_rx.try_recv().is_ok());
    }
}
